import random
print("Number guessing Game!!")

#to generate a random number
number=random.randint(1,9)

#to give the number of chances to henerate the random number
chances = 0

print("Guess a  number")
print("between 1 and 9")

#if chances are less than 5, then allow the users to enter a number
while chances < 5:
    guess=int(input("Guess the Number"),base=10)

    #condition if the number typed by the user is equal to the random number generated by the computer
    if guess == number:
        #break the case or condition and print a message
        print("Congratulations!! You WON")
        break
    elif guess < number:
        print("Yours guess was too low: Guess a number higher than", guess)
    else:
        print("Your guess was too high: Guess a number lesser than", guess)

    #increase the number of chances after every chance
        chances+=1

if not chances < 5:
    print("You lost the match!!.the number was",number)
    
